title: Spencer Ratermann 
image: /assets/spencer_professional_headshot.jpg
description: Masters student aspiring to begin a career in the world of Data Science or Data Analytics 
theme: jekyll-theme-minimal
